# Generated by Django 2.2.13 on 2020-08-29 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Poll text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Choice text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Poll', verbose_name='Poll FK')),
            ],
        ),
    ]
