# Generated by Django 2.2.13 on 2020-08-29 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Choice', verbose_name='Choice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Poll', verbose_name='Poll')),
            ],
        ),
    ]
